


### 회원 전체 조회(Admin)
GET http://localhost:8080/admin/users
Content-Type: application/json
Authorization: {{access_token}}

### 회원 경고 등록(admin)
POST http://localhost:8080/admin/cautions
Content-Type: application/json
Authorization: {{access_token}}

{
  "userId": 1,
  "detail": "당신 블랙 컨슈머야2"
}

### 회원 경고 삭제(admin)
DELETE http://localhost:8080/admin/cautions
Content-Type: application/json
Authorization: {{access_token}}

{
  "warnId": 2
}