@orderId = 3

###로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "userName": "juyeon555",
  "password": "Aa12345678!"
}

> {% client.global.set("access_token", response.headers.valueOf("Authorization")); %}

### 주문내역 생성
POST http://localhost:8080/orders
Content-Type: application/json
Authorization: {{access_token}}

{
  "cost": 68000,
  "discount": 6000,
  "usedMileage": 1000,
  "address": "주연씨의 멋진 집2"
}

### 결제 후 주문내역 조회
GET http://localhost:8080/orders
Content-Type: application/json
Authorization: {{access_token}}

### 결제 후 주문상세 내역 조회
GET http://localhost:8080/orderDetails/{{orderId}}
Content-Type: application/json
Authorization: {{access_token}}
