@orderId = 3
@couponId = 11
###로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "userName": "winner7789",
  "password": "Fb112233!"
}

> {% client.global.set("access_token", response.headers.valueOf("Authorization")); %}

### 카카오페이 결제
POST http://localhost:8080/payments/ready/{{orderId}}/{{couponId}}
Content-Type: application/json
Authorization: {{access_token}}

{
  "taxFreeAmount": 61000
}

### 카카오페이 취소(환불)
POST http://localhost:8080/payments/cancel/{{orderId}}/{{couponId}}
Content-Type: application/json
Authorization: {{access_token}}

{
  "cancelAmount": 61000,
  "cancelTaxFreeAmount": 61000
}
