### 리뷰 작성
POST http://localhost:8080/reviews
Content-Type: application/json
Authorization: {{access_token}}

{
  "productId" : 1,
  "review" : "너무 예뻐요",
  "rating" : 5,
  "reviewImageUrl" : "URL"
}

### 상품별 리뷰 전체 조회
GET http://localhost:8080/reviews/1?page=1

### 내가 작성한 리뷰 조회
GET http://localhost:8080/reviews?page=1
Authorization: {{access_token}}

### 리뷰 수정
PUT http://localhost:8080/reviews
Content-Type: application/json
Authorization: {{access_token}}

{
  "reviewId" : 5,
  "review" : "너무 별로에요",
  "rating" : 3,
  "reviewImageUrl" : "현이하이!@@#@#"
}

### 리뷰 삭제
DELETE http://localhost:8080/reviews
Content-Type: application/json
Authorization: {{access_token}}

{
  "reviewId" : 1
}