
###
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "userName": "winner7789",
  "password": "Fb112233!",
  "name": "류정근",
  "email": "winner7789@gmail.com",
  "phone": "010-6231-4814"
}

###
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "userName": "winner7789",
  "password": "Fb112233!"
}