### 위시리스트 추가
POST http://localhost:8080/wishlists
Content-Type: application/json
Authorization: {{access_token}}

{
  "productId" : 1
}

### 위시리스트 조회
GET http://localhost:8080/wishlists?page=0
Authorization: {{access_token}}

### 위시리스트 삭제
DELETE http://localhost:8080/wishlists
Content-Type: application/json
Authorization: {{access_token}}

{
  "wishId" : 1
}